# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LWfrAHbrEcNVRlbfkat2IICwEWqzEDAj
"""

from sklearn.neural_network import MLPClassifier

X= [[0., 0.], [0., 1.], [1., 0.], [1., 1.]]

Y= [0., 1., 1.,0.]

clf= MLPClassifier(hidden_layer_sizes=(2), solver='lbfgs', random_state=6, learning_rate= 'adaptive', max_iter=500)

clf.fit(X,Y)

clf.predict(X)

#Training error
clf.loss_

#Intercept/Bias values
clf.intercepts_

#Weights to each neuron
clf.coefs_